/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LoginController;
import Model.UserModel;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;
import yahoofinance.Stock;
import yahoofinance.YahooFinance;

/**
 *
 * @author dat26
 */
public class MasterTeleMoneyView extends javax.swing.JFrame {

    /**
     * Creates new form TabbedPane
     */
    UserModel user;
    CardLayout cardLayout;
    TableColumn col;
    public MasterTeleMoneyView() {
        initComponents();
        setTiGia();
        cardLayout = (CardLayout) (pnlCards.getLayout());
        setLocationRelativeTo(null);
        col = tableDanhMuc.getColumnModel().getColumn(2);
        //define the renderer
        col.setCellRenderer(new MasterTeleMoneyView.MyRenderer(Color.red, Color.green));
        
    }

    public MasterTeleMoneyView(UserModel user) {
        this.user = user;
        initComponents();
        setUsername();
        setTiGia();
        cardLayout = (CardLayout) (pnlCards.getLayout());
        setLocationRelativeTo(null);
        col = tableDanhMuc.getColumnModel().getColumn(2);
        //define the renderer
        col.setCellRenderer(new MasterTeleMoneyView.MyRenderer(Color.red, Color.green));
    }

    private void setUsername() {
        txtUsername.setText(user.getUsername());
    }
    
    class MyRenderer extends DefaultTableCellRenderer {

        Color red, green;

        public MyRenderer(Color bg, Color fg) {
            super();
            this.red = bg;
            this.green = fg;
        }

        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            Component cell = super.getTableCellRendererComponent(table, value,
                    isSelected, hasFocus, row, column);
            System.out.println(value);
            if(value == null){
            return cell;
            }
            Float check = Float.parseFloat((String) value);
            if (check >= 0) {
                
                cell.setForeground(green);
            } else {
                cell.setForeground(red);
            }

            return cell;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        pnlCards = new javax.swing.JPanel();
        pnlChiTieu = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pnlVayNo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnlDauTu = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelTiGiaUSDVND = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDanhMuc = new javax.swing.JTable();
        pnlThongKe = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pnlTaiKhoan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtUsername = new javax.swing.JTextPane();
        btnDangXuat = new javax.swing.JButton();
        pnlLeftNav = new javax.swing.JPanel();
        labelMenuVayNo = new javax.swing.JLabel();
        labelMenuDauTu = new javax.swing.JLabel();
        labelMenuThongKe = new javax.swing.JLabel();
        labelMenuTaiKhoan = new javax.swing.JLabel();
        labelLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelMenuChiTieu = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlCards.setBackground(new java.awt.Color(153, 255, 204));
        pnlCards.setMinimumSize(new java.awt.Dimension(199, 200));
        pnlCards.setLayout(new java.awt.CardLayout());

        pnlChiTieu.setBackground(new java.awt.Color(102, 204, 255));

        jLabel8.setText("QUẢN lý chi tiêu");

        javax.swing.GroupLayout pnlChiTieuLayout = new javax.swing.GroupLayout(pnlChiTieu);
        pnlChiTieu.setLayout(pnlChiTieuLayout);
        pnlChiTieuLayout.setHorizontalGroup(
            pnlChiTieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChiTieuLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlChiTieuLayout.setVerticalGroup(
            pnlChiTieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChiTieuLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCards.add(pnlChiTieu, "cardChiTieu");

        pnlVayNo.setBackground(new java.awt.Color(255, 153, 153));

        jLabel9.setText("QUẢN lý vay nợ");

        javax.swing.GroupLayout pnlVayNoLayout = new javax.swing.GroupLayout(pnlVayNo);
        pnlVayNo.setLayout(pnlVayNoLayout);
        pnlVayNoLayout.setHorizontalGroup(
            pnlVayNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVayNoLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlVayNoLayout.setVerticalGroup(
            pnlVayNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVayNoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCards.add(pnlVayNo, "cardVayNo");

        pnlDauTu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel10.setText("QUẢN LÝ CÁC DANH MỤC ĐẦU TƯ");

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel12.setText("SỐ DƯ KHẢ DỤNG: ");

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel13.setText("350.000.000VND");

        labelTiGiaUSDVND.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        labelTiGiaUSDVND.setText("1 USD = 21867VND");

        jScrollPane1.setBackground(new java.awt.Color(255, 204, 204));

        tableDanhMuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, "-5", null},
                {null, null, "9", null},
                {null, null, "-6", null},
                {null, null, "-6", null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableDanhMuc);

        javax.swing.GroupLayout pnlDauTuLayout = new javax.swing.GroupLayout(pnlDauTu);
        pnlDauTu.setLayout(pnlDauTuLayout);
        pnlDauTuLayout.setHorizontalGroup(
            pnlDauTuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDauTuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(355, 355, 355))
            .addGroup(pnlDauTuLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addComponent(labelTiGiaUSDVND)
                .addGap(194, 194, 194))
            .addComponent(jScrollPane1)
        );
        pnlDauTuLayout.setVerticalGroup(
            pnlDauTuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDauTuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(pnlDauTuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(labelTiGiaUSDVND))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );

        pnlCards.add(pnlDauTu, "cardDauTu");

        pnlThongKe.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setText("thống kê");

        javax.swing.GroupLayout pnlThongKeLayout = new javax.swing.GroupLayout(pnlThongKe);
        pnlThongKe.setLayout(pnlThongKeLayout);
        pnlThongKeLayout.setHorizontalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongKeLayout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(jLabel11)
                .addContainerGap(499, Short.MAX_VALUE))
        );
        pnlThongKeLayout.setVerticalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongKeLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel11)
                .addContainerGap(598, Short.MAX_VALUE))
        );

        pnlCards.add(pnlThongKe, "cardThongKe");

        pnlTaiKhoan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel1.setText("Tên đăng nhập: ");

        txtUsername.setEditable(false);
        txtUsername.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        txtUsername.setText("placeholder");
        jScrollPane2.setViewportView(txtUsername);

        btnDangXuat.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTaiKhoanLayout = new javax.swing.GroupLayout(pnlTaiKhoan);
        pnlTaiKhoan.setLayout(pnlTaiKhoanLayout);
        pnlTaiKhoanLayout.setHorizontalGroup(
            pnlTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaiKhoanLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addGroup(pnlTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTaiKhoanLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(428, Short.MAX_VALUE))
        );
        pnlTaiKhoanLayout.setVerticalGroup(
            pnlTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaiKhoanLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addGroup(pnlTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(btnDangXuat)
                .addContainerGap(317, Short.MAX_VALUE))
        );

        pnlCards.add(pnlTaiKhoan, "cardTaiKhoan");

        jSplitPane1.setBottomComponent(pnlCards);

        pnlLeftNav.setBackground(new java.awt.Color(178, 118, 216));
        pnlLeftNav.setMinimumSize(new java.awt.Dimension(180, 100));

        labelMenuVayNo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelMenuVayNo.setForeground(new java.awt.Color(255, 255, 255));
        labelMenuVayNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMenuVayNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/borrow_money_30px.png"))); // NOI18N
        labelMenuVayNo.setText("QUẢN LÝ VAY NỢ");
        labelMenuVayNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelMenuVayNoMousePressed(evt);
            }
        });

        labelMenuDauTu.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelMenuDauTu.setForeground(new java.awt.Color(255, 255, 255));
        labelMenuDauTu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMenuDauTu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invest_30px.png"))); // NOI18N
        labelMenuDauTu.setText("QUẢN LÝ ĐẦU TƯ");
        labelMenuDauTu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelMenuDauTuMousePressed(evt);
            }
        });

        labelMenuThongKe.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelMenuThongKe.setForeground(new java.awt.Color(255, 255, 255));
        labelMenuThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMenuThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chart_30px.png"))); // NOI18N
        labelMenuThongKe.setText("THỐNG KÊ CHUNG");
        labelMenuThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelMenuThongKeMousePressed(evt);
            }
        });

        labelMenuTaiKhoan.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelMenuTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        labelMenuTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/acc_30px.png"))); // NOI18N
        labelMenuTaiKhoan.setText("TÀI KHOẢN");
        labelMenuTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelMenuTaiKhoanMousePressed(evt);
            }
        });

        labelLogo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        labelLogo.setForeground(new java.awt.Color(255, 255, 255));
        labelLogo.setText("TELEMONEY");

        labelMenuChiTieu.setBackground(new java.awt.Color(255, 255, 255));
        labelMenuChiTieu.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelMenuChiTieu.setForeground(new java.awt.Color(255, 255, 255));
        labelMenuChiTieu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMenuChiTieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buying_30px.png"))); // NOI18N
        labelMenuChiTieu.setText("QUẢN LÝ CHI TIÊU");
        labelMenuChiTieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelMenuChiTieuMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlLeftNavLayout = new javax.swing.GroupLayout(pnlLeftNav);
        pnlLeftNav.setLayout(pnlLeftNavLayout);
        pnlLeftNavLayout.setHorizontalGroup(
            pnlLeftNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMenuDauTu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlLeftNavLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLeftNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLeftNavLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLeftNavLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlLeftNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLeftNavLayout.createSequentialGroup()
                                .addComponent(labelLogo)
                                .addGap(32, 32, 32))
                            .addComponent(labelMenuTaiKhoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addComponent(labelMenuVayNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlLeftNavLayout.createSequentialGroup()
                .addComponent(labelMenuThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(labelMenuChiTieu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlLeftNavLayout.setVerticalGroup(
            pnlLeftNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftNavLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(labelLogo)
                .addGap(70, 70, 70)
                .addComponent(jLabel2)
                .addGap(54, 54, 54)
                .addComponent(labelMenuChiTieu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMenuVayNo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMenuDauTu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMenuThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(labelMenuTaiKhoan)
                .addGap(43, 43, 43))
        );

        jSplitPane1.setTopComponent(pnlLeftNav);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelMenuVayNoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMenuVayNoMousePressed
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "cardVayNo");
    }//GEN-LAST:event_labelMenuVayNoMousePressed

    private void labelMenuDauTuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMenuDauTuMousePressed
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "cardDauTu");
    }//GEN-LAST:event_labelMenuDauTuMousePressed

    private void labelMenuThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMenuThongKeMousePressed
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "cardThongKe");
    }//GEN-LAST:event_labelMenuThongKeMousePressed

    private void labelMenuTaiKhoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMenuTaiKhoanMousePressed
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "cardTaiKhoan");
    }//GEN-LAST:event_labelMenuTaiKhoanMousePressed

    private void labelMenuChiTieuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMenuChiTieuMousePressed
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "cardChiTieu");
    }//GEN-LAST:event_labelMenuChiTieuMousePressed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LoginController loginController = new LoginController();
    }//GEN-LAST:event_btnDangXuatActionPerformed
   
    public void setTiGia(){
        try {
            Stock stock = YahooFinance.get("USDVND=X");
            labelTiGiaUSDVND.setText("1 USD = " +stock.getQuote().getPrice()+" VND");
        } catch (IOException ex) {
            Logger.getLogger(MasterTeleMoneyView.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    
    }
    

   

   

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterTeleMoneyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterTeleMoneyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterTeleMoneyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterTeleMoneyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterTeleMoneyView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelMenuChiTieu;
    private javax.swing.JLabel labelMenuDauTu;
    private javax.swing.JLabel labelMenuTaiKhoan;
    private javax.swing.JLabel labelMenuThongKe;
    private javax.swing.JLabel labelMenuVayNo;
    private javax.swing.JLabel labelTiGiaUSDVND;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JPanel pnlChiTieu;
    private javax.swing.JPanel pnlDauTu;
    private javax.swing.JPanel pnlLeftNav;
    private javax.swing.JPanel pnlTaiKhoan;
    private javax.swing.JPanel pnlThongKe;
    private javax.swing.JPanel pnlVayNo;
    private javax.swing.JTable tableDanhMuc;
    private javax.swing.JTextPane txtUsername;
    // End of variables declaration//GEN-END:variables
}
